#!/bin/bash

##############
# Author: Nikhil
# Date: 22/08/2025

 write a shell script to printnumbers divided by 3 & 5 and not 15

#############


# divisble by 3 , divisible by 5 , not  3*5=15

for i in {1..100}; do
if ([ `expr $i % 3` == 0 ] || [ `expr $i % 5` == 0 ]) && [ `expr $i % 15` != 0 ];
then
         echo $i
fi;
done

